

development:
  adapter: postgresql
  encoding: utf8
  database: lithirst_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: lithirst_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: lithirst_production
  host: localhost
  pool: 5
  timeout: 5000
